graph LR
    A[数据集（n=770）] -->|经纬度| B{"WorldClim v2.0[1]"}
    A[数据集（n=770）] -->|经纬度| C{"HWSD[2] v1.2"}

    B --> D{"气候变量"}
    C --> E{"土壤变量"}

    D --> F{"中国植物病害数据"}
    E --> F{"中国植物病害数据"}

    F --> G{"机器学习模型"}

